title: 0xk4k45h1
description: "My redteaming stuff"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/kakashi.jpg"

# Social Links
email: youssifseliem@gmail.com
github_username: YoussifSeliem
twitter_username: youssifseliem
instagram_username: instagram
linkedin_username: Youssif Seliem
facebook_username: youssifseliem

# External API
giscus_repo:
giscus_repoId:
giscus_category:
giscus_categoryId:
goatcounter_code:
google_analytics:

# # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                 #
#   Not recommended to touch the materials below  #
#                                                 #
#    Any changes may contribute to malfunction    #
#                                                 #
# # # # # # # # # # # # # # # # # # # # # # # # # #

# Build settings

# If you want to deploy Git Page, but choosing the second Installation method (described in README.md)
# rather than fork, then replace the below line with `remote_theme: byanko55/jekyll-theme-satellite`.
# Otherwise, DO NOT change it.
theme: jekyll-theme-satellite

exclude:
  - _posts

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
